# A sample 
source "https://rubygems.org"

gem "sinatra"
gem "shotgun"
gem "sqlite3"
gem "datamapper"
gem "dm-sqlite-adapter"
gem "builder"
gem "rack-flash"
gem "sinatra-redirect-with-flash"
gem "sinatra-flash"
